sudo: required

services:
  - docker

before_install:
  - docker build -t movit-devops -f Dockerfile .
  - docker run -d --name app movit-devops

script:
  - docker exec app python -m unittest discover

after_script:
  - docker rm -f app