sudo: required
services:
- docker
language: python
deploy:
  provider: gae
  project: ethereal-brace-240418
  keyfile: gce.json
  verbosity: debug
  on: master
before_install:
- openssl aes-256-cbc -K $encrypted_2a468507c033_key -iv $encrypted_2a468507c033_iv
  -in gce.json.enc -out gce.json -d